### ISSUE TITLE
Links on start page broken?

### ISSUE THREAD

**Issue by lostdesign** [vuejs/v3-migration-guide#1]
Almost ever link on the homepage throw a 404 on https://v3-migration.vuejs.org/ - e.g. https://vuejs.org/api/sfc-script-setup.html which should be https://v3.vuejs.org/api/sfc-script-setup.html#sfc-script-setup

But I assume there is some switch happening soon? At least there has been certain tweets by Evan on twitter. Just wanted to point out.

**Comment by NaincyKumariKnoldus** [comment]
Hey @lostdesign Can I change the link?

**Comment by lostdesign** [comment]
> Hey @lostdesign Can I change the link?

Not sure, It may be desired as there might be a switch from v3.vuejs.org to just vuejs.org in the near future.

As I am no maintainer, I cannot answer that.

**Comment by NaincyKumariKnoldus** [comment]
okay Can you confirm from the maintainer plz?

**Comment by LinusBorg** [comment]
> Not sure, It may be desired as there might be a switch from v3.vuejs.org to just vuejs.org in the near future.

This is correct.
