### ISSUE TITLE
Links in overview + and to v3 docs are broken

### ISSUE THREAD

**Issue by Narretz** [vuejs/v3-migration-guide#3]
All the links under Notable New Features  are broken, e.g. [Composition API](https://vuejs.org/guide/extras/composition-api-faq.html)

Also, the link to "Vue 3 Docs" is broken, it goes to vuejs.org, but the home of v3 is v3.vuejs.org.

**Comment by LinusBorg** [comment]
The home will be vuejs.org when this guide will actually be public.

**Comment by Narretz** [comment]
Wdm "when this guide will actually be public". It's already public, I found it via a link on the core repository readme: https://github.com/vuejs/core

And the links in the overview are still broken regardless.

**Comment by LinusBorg** [comment]
I want aware this is already being linked to from somewhere 👀

My perspektive was that this guide would only be linked to once we switch to the new docs on February 7th, until then it's still part of the current V3 docs at v3.vuejs.org.

We're kind of in the middle of the switch preparations.

I'll confer with the team how to handle it.
